export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"

export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE"
export const GET_EMPLOYEE = "GET_EMPLOYEE"
export const GET_ALL_EMPLOYEE = "GET_ALL_EMPLOYEE"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"